/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Získat seznam všech událostí */
        get: operations["listEvents"];
        put?: never;
        /** Vytvořit novou událost */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Získat detail jedné události podle ID */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: number;
            message: string;
        };
        UserRecord: {
            name: string;
            /** @enum {string} */
            answer: "yes" | "no" | "if-needed";
        };
        DateRecord: {
            /**
             * Format: int64
             * @description Unix epoch v milisekundách
             */
            timestamp: number;
            records: components["schemas"]["UserRecord"][];
        };
        Event: {
            id: number;
            title: string;
            location?: string | null;
            dates: components["schemas"]["DateRecord"][];
        };
        NewEvent: {
            title: string;
            location?: string | null;
            /** @description Pole timestampů (ms) navrhovaných termínů */
            dates: number[];
            /** @description Jméno zakladatele/organizátora (volitelné) */
            name?: string;
        };
    };
    responses: {
        /** @description Zdroj nenalezen */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "code": 404,
                 *       "message": "Not Found"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Neplatná data požadavku */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "code": 400,
                 *       "message": "Invalid payload"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Neočekávaná chyba serveru */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "code": 500,
                 *       "message": "Internal Server Error"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description ID události */
        IdParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seznam událostí v obálce `items` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Event"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["ServerError"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewEvent"];
            };
        };
        responses: {
            /** @description Událost úspěšně vytvořena */
            201: {
                headers: {
                    /** @description URL nově vytvořeného zdroje */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["ServerError"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID události */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detaily události */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
}
